### ISSUE TITLE
Out of canvas draw issue

### ISSUE THREAD

**Issue by henrikc79** [trikberg/draw#1]
While drawing a continuous line from within the canvas and moving outside of the canvas and back in, the continuous line gets interrupted.
The intended (from a game flow perspective) manner would be to resume painting as if the cursor did not disappear from the new location where it enters.

A side effect of this bug is that yes, while it is interrupted while drawing, it is remembered behind the scene as a line being drawn between the canvas exit point and entry point when later going through an UNDO operation (but only if the operation that is being undo'ed is a FILL operation).

I can demonstrate the issue if you like in a video call.

**Comment by trikberg** [comment]
Fixed (but not yet deployed).
