### ISSUE TITLE
Fill causes infinite loop and eventual OOM

### ISSUE THREAD

**Issue by henrikc79** [trikberg/draw#4]
While playing around with the canvas, creating many overlapping lines in a pattern that can be seen in this image:
![DrawFiOOM_Scenario](https://user-images.githubusercontent.com/19327720/148310206-9aec352d-b2f9-4cc9-bb58-2a6cba51077b.png)

Then starting to fill randomly within the confines of the pattern, I only got to click 4 times before the window froze and performed zero draw operations after that moment.
While I was investigating the issue, looking at Chrome Task Manager, I saw a huge CPU load on the tab for Draw.fi.
![DrawFi_ChromeTaskManager](https://user-images.githubusercontent.com/19327720/148310389-8c7f639c-95b2-48ce-bdaa-9714140265c9.png)

Meanwhile, the memory was stable. But after a few mins, the tab crashed with OOM exception:
![DrawFiOOM](https://user-images.githubusercontent.com/19327720/148310456-c009c3c1-b3e2-40a0-8f86-a6f002dbb540.png)

I then inspected with Process Explorer, and it revealed the computer had used an extra 4GB of memory.
![DrawFiOOM_MemUsage](https://user-images.githubusercontent.com/19327720/148310430-5e704a98-1ac7-4d1f-af8d-2ce49dbaf833.png)

This is admittedly not a normal mode of operation, but it could happen to regular users in some scenarios(filling a figure with lines instead of fill).

**Comment by trikberg** [comment]
This could happen when start pixel and fill color where very close, usually with a small difference in the alpha channel due to anti-aliasing. Fixed (or at the very least much harder to repeat).
